### PR TITLE
Rename cnbi to cre

### PR DESCRIPTION
**Pull request by VannTen**
Scripted rename using https://github.com/thoth-station/meteor-operator/pull/115#issuecomment-1315346136

### CODE REVIEW

**Comment by VannTen** [comment]
redone after merging #108

**Comment by codificat** [comment]
Let's
/hold
just a bit more until #106 is in and we include it in the renaming

**Comment by VannTen** [comment]
/hold
(until #106 is merged, as discutted in chat)

**Comment by VannTen** [comment]
I'll redo the PR if we we merge #139 before that

**Comment by VannTen** [comment]
Redone after #147

**Comment by codificat** [comment]
tested and working
/lgtm
/approve

**Pull request merged**
