### PR TITLE
Add nfs provisioner script

### PR DESCRIPTION
**Pull request by VannTen**
The script should be **mostly** idempotent

### CODE REVIEW

**Comment by VannTen** [comment]
An ansible playbook might be more apt, but I'm not sure it's worth it

**Review by codificat — COMMENTED** [review]
/approve

only a minor / optional code in the README. But the file is failing pre-commit checks at the moment, so I'll lgtm the updated version anyway

**Comment by VannTen** [comment]
Good points.
I put the requirements in the script header, in order to avoid clutter
the README

**Pull request merged**
