### PR TITLE
Use pipeline CRD directly from tekton-pipeline

### PR DESCRIPTION
**Pull request by VannTen**
This use the Tekton Pipeline CRD from the go module tekton-pipelines instead of having the CRD in our git repo.

That way we should avoid getting out of sync between the CRD and the modules.

One little annoyance though: at first I tried to dynamically get the `tekton-pipeline` version in the test code (using https://pkg.go.dev/runtime/debug#BuildInfo)
but looks like it does not work (test binary built without module support ? I don't know)

/kind cleanup

### CODE REVIEW

**Comment by VannTen** [comment]
@goern @codificat wdyt ?

**Comment by goern** [comment]
/lgtm
/approve

@VannTen could you have a look for a mapping of OpenShift Pipeline releases to Tekton versions?

**Comment by VannTen** [comment]
> could you have a look for a mapping of OpenShift Pipeline releases to Tekton versions?

https://docs.openshift.com/container-platform/4.12/cicd/pipelines/op-release-notes.html

Looks like the version of the Pipelines composant is the tektoncd/pipeline version, but that's not obvious...

**Pull request merged**
