### PR TITLE
fix/makefile install pipelines

### LINKED ISSUE #142: Makefile targets `{un,}install-pipelines` use `hack/` instead of `pipelines/pipelines`
/kind bug
/wg cre

### PR DESCRIPTION
**Pull request by VannTen**
Fix #142

### CODE REVIEW

**Comment by codificat** [comment]
What about an alternative approach here:
- remove the make targets to (un)install the pipelines
- include the pipelines as part of the deployment

That way, `make deploy` would behave the same way as an odh deployment via kfdef.

What I mean is to add this to the config/base/kustomization file:

```yaml
bases:
  # ...
  # Install the meteor pipeline manifests
  - ../../pipelines/base
```

WDYT?

**Comment by VannTen** [comment]
That's way better, unless I misunderstand something about the structure
in `config/` ***@***.*** wdyt ?)
Thanks Pep !

**Comment by codificat** [comment]
I was a bit too optimistic with the proposal: it's not that simple, because when adding it to the overall kustomization, then the same [name prefixes specified in kustomize](https://github.com/thoth-station/meteor-operator/blob/7872d19b4c073ab37d1cc23d30868f9d7c40d168/config/base/kustomization.yaml#L4-L9) apply to the pipelines.

The result is that the pipelines get installed like this:

```
$ oc get pipeline
NAME                           AGE
meteor-operator-cnbi-gitrepo   32m
meteor-operator-cnbi-import    32m
```

i.e. with the `meteor-operator-` prefix.

I don't think that's actually a bad thing per se, and we might actually prefer it!

However, the controller currently expects pipeline names without these prefixes, so this change would require an update to the controller when creating the PipelineRuns.

Should we add that change to the controller?  It might be an opportunity / excuse to address https://github.com/thoth-station/meteor-operator/issues/97 at the same time (not completely directly related, but close enough).

**Comment by VannTen** [comment]
Oh yeah. I forgot that kustomize add names prefix everywhere. While I find this absurd (namespaces are precisely for this), that's trivial to fix. I wouldn't solve #97 at the same time though, that one requires us to answer https://github.com/thoth-station/meteor-operator/issues/97#issuecomment-1305494252 first.

**Comment by VannTen** [comment]
Btw, I'm currently having a discussion on that subject here: https://github.com/operator-framework/operator-sdk/issues/6186

**Comment by VannTen** [comment]
Actually it does not work either, because the Task also get prefixed and we're not using the prefix in the pipelines spec. 

Honestly, I'd rather not use a prefix at all ; if there is good reason for it, it seems there is some undocumented stuff to skipPrefix on some resources.

@goern @codificat wdyt ?

**Comment by codificat** [comment]
/lgtm
/approve

thanks!

**Pull request merged**
