### PR TITLE
just renamed condition_const of CRE

### PR DESCRIPTION
**Pull request by goern**
SSIA

Signed-off-by: Christoph Görn <goern@redhat.com>

### CODE REVIEW

**Comment by codificat** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**

@VannTen I feel you should be an approver here... PRs welcome :)  Meanwhile,
/approve

**Comment by VannTen** [comment]
Pre-commit looks fine locally, maybe prow is kicking the bucket again ?
/retest

**Pull request merged**
