### PR TITLE
refactore PipelineRun Parameter creation

### PR DESCRIPTION
**Pull request by goern**
Depends-On: #115 

- :pencil: rename test functions
- :recycle: refactor out PipelineRun Parameter creation
- :recycle: refactor out how PipelineRun is generated

### CODE REVIEW

**Comment by VannTen** [comment]
Can we take out the rename to CRE (already has #115 ) and the config for golangci-lint in separate PRs ?

**Comment by goern** [comment]
reverted golangci config, and [2a2cf77](https://github.com/thoth-station/meteor-operator/pull/128/commits/2a2cf77474c0c9044df9b72775874944c565eec1) should be part of #115

**Comment by VannTen** [comment]
This has been superseded, right ?

**Comment by goern** [comment]
very true! thx for the reminder!

/close

**Pull request closed without merging**
